[package]
name = "mission_control"
version = "0.0.12"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
ic-ledger-types.workspace = true
serde.workspace = true
futures = "0.3.28"
junobuild-shared = { path = "../libs/shared" }
