[package]
name = "mission_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.3"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
ic-ledger-types = "0.2.0"
serde = "1.0.145"
lazy_static = "1.4.0"
shared = { path = "../shared" }
