[package]
name = "mission_control"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.3"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.10"
ic-ledger-types = "0.4.2"
serde = "1.0.162"
futures = "0.3.28"
shared = { path = "../shared" }
