[package]
name = "shared"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.3"
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.8"
ic-ledger-types = { git = "https://github.com/dfinity/cdk-rs", rev = "75e84bc9cf8df154e569f725698d3e73fc1feaef" }
serde = "1.0.145"
futures = "0.3.25"
