[package]
name = "orbiter"
version = "0.0.7"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
serde.workspace = true
ic-stable-structures.workspace = true
lazy_static = "1.4.0"
ciborium = "0.2.1"
isbot = "0.1.3"
url = "2.4.0"
regex = "1.9.3"
junobuild-shared = { path = "../libs/shared" }
