[package]
name = "orbiter"
version = "0.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.4"
ic-cdk-macros = "0.8.1"
serde = "1.0.190"
lazy_static = "1.4.0"
ic-stable-structures = "0.5.6"
ciborium = "0.2.1"
isbot = "0.1.3"
url = "2.4.0"
regex = "1.9.3"
shared = { path = "../shared" }
