[package]
name = "console"
version = "0.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.1"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.0"
ic-ledger-types = "0.7.0"
serde = "1.0.162"
serde_cbor = "0.11.2"
shared = { path = "../shared" }
